### ISSUE TITLE
Logging is done directly to console rather than to logger

### ISSUE THREAD

**Issue by dmidura** [LambdaTest/lambdatest-maven-tunnel#24]
I am using this library to create and tear down an LT tunnel in my mobile automation framework. My issue is that the library is currently printing all log calls to console (via System.out.println) rather than printing log calls to a standard logger like log4j2 or slf4j. Can you please update the library to log comments to logger so that comments can be turned on/off at will? 

Thanks,

Dani

**Comment by Shivanshu-lambdatest** [comment]
Thanks, @dmidura for highlighting the issue, we will fix it in the next release

**Comment by Shahnawaz-Sk** [comment]
@dmidura We have reduced the number of logs the tunnel generates in the new version `2.0.2`. Hope this serves the purpose.
