### ISSUE TITLE
Recursive loop during tunnel update

### ISSUE THREAD

**Issue by dmidura** [LambdaTest/lambdatest-maven-tunnel#25]
When running the tunnel, if the tunnel determines it needs to update but cannot pull down the update file, then the code runs through a recursive never-ending loop. Please add a timeout.

**Comment by Shahnawaz-Sk** [comment]
Sure @dmidura, we will look into this issue and resolve it.

**Comment by Shahnawaz-Sk** [comment]
This issue is not reproducible as of now at our end. Closing this for now.
